"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "current"
scan_timeout = 120

format = """
[](bg_blue)\
$os\
$username\
[](bg:bg_selection fg:bg_blue)\
$directory\
[](bg:bg_purple fg:bg_selection)\
$git_branch\
$git_status\
[](fg:bg_purple)\
$cmd_duration\
$line_break$character"""

# Destroys resize bug permanently
right_format = """"""

[os]
disabled = false
style = "bg:bg_blue fg:fg_dark"
format = "[$symbol]($style)"

[os.symbols]
Fedora = " "

[username]
show_always = true
style_user = "bg:bg_blue fg:fg_dark"
format = "[$user]($style)"

[directory]
style = "bg:bg_selection fg:fg_light"
format = "[ $path ]($style)"
truncation_length = 3
substitutions = { "Documents" = "󱔗 ", "Downloads" = " ", "Music" = "󰎆 ", "Pictures" = " ", "projects" = "󱂛 ", "college" = "󰑴 ", "dotfile" = "󰒓 " }

[git_branch]
symbol = " "
style = "bg:bg_purple fg:fg_dark"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:bg_purple fg:fg_dark"
format = "[$all_status$ahead_behind ]($style)"

[cmd_duration]
min_time = 2_000
style = "bold yellow"
format = "[ 󱎫 $duration ]($style)"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "
