# Gruvbox Material Dark Kitty Theme
foreground #dfbf8e
background #282828
cursor #dfbf8e
cursor_text_color #282828

selection_foreground #282828
selection_background #dfbf8e

# Black
color0 #32302f
color8 #928374

# Red
color1 #ea6962
color9 #ea6962

# Green
color2 #a9b665
color10 #a9b665

# Yellow
color3 #d8a657
color11 #d8a657

# Blue
color4 #7daea3
color12 #7daea3

# Magenta
color5 #d3869b
color13 #d3869b

# Cyan
color6 #89b482
color14 #89b482

# White
color7 #dfbf8e
color15 #a89984
